### ISSUE TITLE
Docker warning undefined variable.

### ISSUE THREAD

**Issue by WindShiba** [EventAccess/Registrering#17]
Terminal gives a warning twice when running the docker-compose build command, in ./Meta/Registration.
_**`level=warning msg="The \"q6\" variable is not set. Defaulting to a blank string."`**_
I cant see any variables named q6 that needs to be set.

**Comment by WindShiba** [comment]
fixed.

**Comment by oddstr13** [comment]
Fixed *how*? (For future reference)
