### ISSUE TITLE
Next js container breaking on Deamon -d argument

### ISSUE THREAD

**Issue by WindShiba** [EventAccess/Registrering#46]
Next js breaks on deamon. Just remove the -d when you run the command for now.
> `docker compose --profile dev up -d` `docker compose --profile prod up -d` 
>  docker compose --profile dev up -d docker compose --profile prod up

**Comment by oddstr13** [comment]
unable to reproduce, need more details

**Comment by WindShiba** [comment]
It seems to have magically resolved itself over time, though I’m not sure why it behaved that way in the first place.
